<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Student List Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'DejaVu Sans', Arial, sans-serif;
            font-size: 11px;
            line-height: 1.4;
            color: #333;
        }
        
        .container {
            padding: 20px;
        }
        
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 15px;
        }
        
        .school-name {
            font-size: 18px;
            font-weight: bold;
            color: #1e40af;
            margin-bottom: 5px;
        }
        
        .report-title {
            font-size: 16px;
            font-weight: bold;
            color: #1f2937;
            margin-top: 10px;
        }
        
        .report-info {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .info-left, .info-right {
            display: table-cell;
            width: 50%;
            vertical-align: top;
        }
        
        .info-item {
            margin-bottom: 5px;
            font-size: 10px;
        }
        
        .filters-section {
            background: #f8fafc;
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 20px;
            border: 1px solid #e2e8f0;
        }
        
        .filters-title {
            font-weight: bold;
            color: #374151;
            margin-bottom: 8px;
            font-size: 12px;
        }
        
        .filters-grid {
            display: table;
            width: 100%;
        }
        
        .filter-item {
            display: table-cell;
            width: 33.33%;
            padding-right: 10px;
            font-size: 10px;
        }
        
        .students-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        .students-table th {
            background: #f1f5f9;
            color: #374151;
            font-weight: 600;
            padding: 8px 6px;
            text-align: left;
            border: 1px solid #d1d5db;
            font-size: 10px;
        }
        
        .students-table td {
            padding: 6px;
            border: 1px solid #e5e7eb;
            font-size: 10px;
            vertical-align: top;
        }
        
        .students-table tbody tr:nth-child(even) {
            background: #f9fafb;
        }
        
        .status-badge {
            padding: 2px 6px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: 500;
        }
        
        .status-enrolled {
            background: #dcfce7;
            color: #166534;
        }
        
        .status-pending {
            background: #fef3c7;
            color: #92400e;
        }
        
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #e5e7eb;
            font-size: 9px;
            color: #6b7280;
        }
        
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Header -->
        <div class="header">
            <div class="school-name">OPOL NATIONAL SECONDARY TECHNICAL SCHOOL</div>
            <div class="report-title">{{ $reportData['title'] }}</div>
        </div>

        <!-- Report Information -->
        <div class="report-info">
            <div class="info-left">
                <div class="info-item"><strong>Generated on:</strong> {{ $reportData['generated_at'] }}</div>
                <div class="info-item"><strong>Generated by:</strong> {{ $reportData['generated_by'] }}</div>
            </div>
            <div class="info-right">
                <div class="info-item"><strong>Total Students:</strong> {{ $reportData['total_students'] }}</div>
                <div class="info-item"><strong>School Year:</strong> {{ $reportData['filters']['school_year'] }}</div>
            </div>
        </div>

        <!-- Applied Filters -->
        <div class="filters-section">
            <div class="filters-title">Applied Filters:</div>
            <div class="filters-grid">
                <div class="filter-item"><strong>Strand:</strong> {{ $reportData['filters']['strand'] }}</div>
                <div class="filter-item"><strong>Section:</strong> {{ $reportData['filters']['section'] }}</div>
                <div class="filter-item"><strong>Subject:</strong> {{ $reportData['filters']['subject'] }}</div>
            </div>
        </div>

        <!-- Students Table -->
        @if(count($reportData['students']) > 0)
            <table class="students-table">
                <thead>
                    <tr>
                        <th style="width: 25%">Full Name</th>
                        <th style="width: 15%">LRN</th>
                        <th style="width: 15%">Strand</th>
                        <th style="width: 12%">Year Level</th>
                        <th style="width: 15%">Section</th>
                        <th style="width: 18%">Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($reportData['students'] as $student)
                        <tr>
                            <td>{{ $student['full_name'] }}</td>
                            <td>{{ $student['lrn'] }}</td>
                            <td>{{ $student['strand'] }}</td>
                            <td>{{ $student['year_level'] }}</td>
                            <td>{{ $student['section'] }}</td>
                            <td>
                                <span class="status-badge {{ in_array($student['enrollment_status'], ['enrolled', 'approved']) ? 'status-enrolled' : 'status-pending' }}">
                                    {{ ucfirst($student['enrollment_status']) }}
                                </span>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <div style="text-align: center; padding: 40px; color: #6b7280;">
                <p style="font-size: 14px; font-weight: 600;">No students found</p>
                <p style="font-size: 12px;">No students match the selected filter criteria.</p>
            </div>
        @endif

        <!-- Footer -->
        <div class="footer">
            <p>This report was generated by the ONSTS Student Information System</p>
            <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
        </div>
    </div>
</body>
</html>
